# .jira/config.yml
deployments:
  environmentMapping:
    development:
      - "dev"
      - "dev*"
    testing:
      - "qa"
      - "qa*"
    staging:
      - "staging"
      - "staging*"
    production:
      - "main"       
      - "prod"
      - "prod-*"
