deployments:
  environmentMapping:
    development:
      - "dev*"
      - "dev"
      - "Entwicklung"
      - "desenvolvimento"
      - "дев"
    testing:
      - "testes"
      - "qa"
      - "qa*"
      - "Test"
      - "TST-*"
      - "тест"
    staging:
      - "Pre-Prod"
      - "STG-*"
      - "staging"
      - "staging*"
    production:
      - "Produktion"
      - "produção"
      - "продакшн"
      - "PROD-*"
