name: Jira-Linked Deployments

on:
  push:
    branches:
      - main
      - dev
      - qa
      - staging

jobs:
  emit-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        id: create_deployment
        uses: chrnorm/deployment-action@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref:   ${{ github.sha }}
          # if we're on main, call it "production", otherwise the branch name
          environment: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref_name }}

      - name: Mark Deployment Successful
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.create_deployment.outputs.deployment_id }}
          state: success
